Add redirection management
Evarisk/Saturne pull request #1007
Opened 2024-07-01 16:03 UTC by theodaviddd

2024-07-16 09:41 UTC, theodaviddd commented
Après le rework suivant : 

```
    /**
     *  Overloading the beforeLoginAuthentication function : replacing the parent's function with the one below
     *
     * @param  array        $parameters Hook metadatas (context, etc...)
     * @param  CommonObject $object     Current object
     * @param  string       $action     Current action
     * @return int                      0 < on error, 0 on success, 1 to replace standard code
     */
    public function llxHeader(array $parameters, $object, string $action) {

        require_once __DIR__ . '/saturneredirection.class.php';

        $saturneRedirection = new SaturneRedirection($this->db);

        $redirectionList = $saturneRedirection->fetchAll();
        if (is_array($redirectionList) && !empty($redirectionList)) {
            foreach($redirectionList as $redirection) {
                echo '<pre>';
                print_r($_SERVER['REQUEST_URI']);
                echo '</pre>';
                exit;
            }
        }

        return 0; // or return 1 to replace standard code
    }
```

On se rend compte que lorsqu'on appelle une URL qui n'existe pas, le serveur renvoie une 404, avant même de charger l'environnement dolibarr => On ne peut donc pas gérer les redirections à la volée en PHP.

2024-07-16 09:56 UTC, theodaviddd commented
La seule solution est d'écrire une ligne dans l'htaccess de chaque installation redirigeant les 404 vers un fichier php du module et de charger le main dans ce fichier. On pourra check le http referer / request uri pour rediriger le cas échéant

2024-08-27 09:05 UTC, evarisk-micka requested changes

2024-08-27 09:05 UTC, evarisk-micka commented on sql/redirections/llx_saturne_redirection.key.sql
> +ALTER TABLE llx_saturne_redirection ADD INDEX idx_saturne_redirection_ref (ref);
y'a pas de ref sur redirections

2024-08-27 09:05 UTC, evarisk-micka commented on sql/redirections/llx_saturne_redirection.key.sql
> +ALTER TABLE llx_saturne_redirection ADD UNIQUE INDEX uk_saturne_redirection_ref (ref, entity);
toujours pas

2024-09-10 09:21 UTC, theodaviddd commented
02fe6b7a448e6a2d91aaef8597a6ab6063ca2f60

2024-09-18 17:54 UTC, merged