Fix enhance document list
Evarisk/Saturne pull request #1021
Opened 2024-07-23 15:57 UTC by theodaviddd

2024-08-13 07:47 UTC, theodaviddd commented
- [ ] Pagination à côté du titre de la liste
- [ ] Garder tous les paramètres d'URL
- [ ] Pagination mini 0 => 1
- [ ] Pagination dolibarr friendly ?
- [ ] Search & cancel dolibarr friendly
- [ ] Get title field list

2024-08-27 09:50 UTC, evarisk-micka requested changes

2024-08-27 09:50 UTC, evarisk-micka commented on lib/documents.lib.php
> +            $querySeparator = (strpos($_SERVER['REQUEST_URI'], '?') === false) ? '?' : '&';
il sert à rien ici

2024-08-27 09:50 UTC, evarisk-micka commented on lib/documents.lib.php
> +    $page = GETPOST('page', 'int') ?: 1;
psr12

2024-08-27 09:50 UTC, evarisk-micka commented on lib/documents.lib.php
> +    return $out;
un espace entre le return

2024-08-27 09:50 UTC, evarisk-micka commented on lib/documents.lib.php
> +    return $out;
+psr12

2024-09-10 09:09 UTC, theodaviddd commented
b285c8a3cc2e55f733afb779eac7be47e4d1010b

2026-05-29 13:34 UTC, closed without merging