Add qr code management
Evarisk/Saturne pull request #1046
Opened 2024-08-06 14:20 UTC by theodaviddd

2024-08-27 09:37 UTC, evarisk-micka requested changes

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +/* Copyright (C) 2021-2023 EVARISK
2024

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> + * \brief   Saturne redirections page
est-ce que j'aurais copié mon fichier et fais des erreurs ? ça m'étonnerait

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +// Load Module libraries
Saturne Libraries

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +$url = GETPOST('url', 'alpha');
psr12

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +    $saturneQRCode->status = 1;
psr12

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +    $saturneQRCode->url = GETPOST('url');
tu l"as stocké, tu peux faire pareil pour id

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +    setEventMessage('QRCodeRemoved');
langs->trans

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +$help_url = 'FR:Module_' . $moduleName;
psr12 + helpUrl

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +                                <!-- Le PDF sera affiché ici dans un iframe -->
c'est totalement illégal de print comme ça du html (+remove commentaire)

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +print '<td class="center">' . $langs->trans('QR Code') . '</td>';
espace en trop

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +            print '<button type="submit" class="butAction">' . $langs->trans('Save') . '</button>';
wpeo-button dans le doute

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +
trop de commentaires et un espace en trop et class="" vide

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +print '<input type="submit" class="button" value="' . $langs->trans('Add') . '">';
wpeo-button

2024-08-27 09:37 UTC, evarisk-micka commented on admin/qrcode.php
> +print '</td><td class="center">';
colspan

2024-08-27 09:37 UTC, evarisk-micka commented on class/saturneqrcode.class.php
> +/* Copyright (C) 2021-2023 EVARISK <technique@evarisk.com>
2024

2024-08-27 09:37 UTC, evarisk-micka commented on class/saturneqrcode.class.php
> +    public $output = '';
kèsseussé ?

2024-08-27 09:37 UTC, evarisk-micka commented on class/saturneqrcode.class.php
> +    public string $picto = 'fontawesome_fa-forward_fas_#d35968';
bad picto (+ commentaire au dessus)

2024-08-27 09:37 UTC, evarisk-micka commented on class/saturneqrcode.class.php
> +    public $fields = [
vérifier les positions (et quand même le reste des fields au cas ou)

2024-08-27 09:37 UTC, evarisk-micka commented on js/modules/document.js
> +  $(document).on( 'keydown', '#change_pagination', window.saturne.document.changePagination );
c'est dans la pr document y'aura ptet un conflit

2024-08-27 09:37 UTC, evarisk-micka commented on js/modules/qrcode.js
> + * @version 1.2.0
mauvaises versions partout

2024-08-27 09:37 UTC, evarisk-micka commented on js/modules/qrcode.js
> +    const a = document.createElement('a');
mauvais nom de variable

2024-08-27 09:37 UTC, evarisk-micka commented on langs/fr_FR/saturne.lang
> +QRCodeCreated = QR Code créé
SaturneObjectCreated
+ PSR12

2024-08-27 09:37 UTC, evarisk-micka commented on sql/qrcode/index.php
> +//Silence is golden pear
apple

2024-08-27 09:37 UTC, evarisk-micka commented on sql/qrcode/llx_saturne_qrcode.key.sql
> +ALTER TABLE llx_saturne_qrcode ADD INDEX idx_saturne_object_qrcode_ref (ref);
toujours pas de ref

2024-08-27 09:37 UTC, evarisk-micka commented on sql/qrcode/llx_saturne_qrcode.key.sql
> +ALTER TABLE llx_saturne_qrcode ADD INDEX idx_saturne_object_qrcode_status (status);
pas de status non plus

2024-08-27 09:37 UTC, evarisk-micka commented on class/saturneqrcode.class.php
> +        'status'            => ['type' => 'smallint',     'label' => 'Status',           'enabled' => 1, 'position' => 70,  'notnull' => 1, 'visible' => 2, 'default' => 0, 'index' => 1, 'validate' =>
mauvais arrayofkeyval + si tu hard delete pas besoin de status

2024-08-27 09:37 UTC, evarisk-micka commented on sql/qrcode/llx_saturne_qrcode.sql
> +    status          integer DEFAULT 1 NOT NULL,
Soit y'a un status mais il sert soit on l'enlève

2024-08-27 09:37 UTC, evarisk-micka commented on sql/qrcode/llx_saturne_qrcode.sql
> +-- Copyright (C) 2021-2023 EVARISK <technique@evarisk.com>
2024

2024-09-10 09:07 UTC, theodaviddd commented
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on admin/qrcode.php
> +/* Copyright (C) 2021-2023 EVARISK
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on admin/qrcode.php
> + * \brief   Saturne redirections page
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on admin/qrcode.php
> +// Load Module libraries
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on admin/qrcode.php
> +    $saturneQRCode->status = 1;
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on sql/qrcode/llx_saturne_qrcode.key.sql
> +ALTER TABLE llx_saturne_qrcode ADD INDEX idx_saturne_object_qrcode_ref (ref);
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on sql/qrcode/llx_saturne_qrcode.key.sql
> +ALTER TABLE llx_saturne_qrcode ADD INDEX idx_saturne_object_qrcode_status (status);
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on class/saturneqrcode.class.php
> +        'status'            => ['type' => 'smallint',     'label' => 'Status',           'enabled' => 1, 'position' => 70,  'notnull' => 1, 'visible' => 2, 'default' => 0, 'index' => 1, 'validate' =>
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on sql/qrcode/llx_saturne_qrcode.sql
> +    status          integer DEFAULT 1 NOT NULL,
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2024-11-19 13:57 UTC, theodaviddd commented on sql/qrcode/llx_saturne_qrcode.sql
> +-- Copyright (C) 2021-2023 EVARISK <technique@evarisk.com>
6e3aefbb7167e9c5e376c58f773f5168f0e44ff6

2026-06-09 13:13 UTC, closed without merging