#972 [Lib] fix: bug not good path for photos
Evarisk/Saturne pull request #973
Opened 2024-06-08 21:39 UTC by Charlless22

2024-06-13 09:37 UTC, evarisk-micka requested changes

2024-06-13 09:37 UTC, evarisk-micka commented on lib/saturne_functions.lib.php
> +        $subDir     = $object->element_type . '/'. $object->ref . '/';
Tout casser pour réparer un truc ?

2024-06-13 09:37 UTC, evarisk-micka commented on lib/saturne_functions.lib.php
> +
Attention aux espaces inutiles

2024-06-24 09:42 UTC, closed without merging

2024-06-24 09:42 UTC, nicolas-eoxia commented
Le fix doit être fais dans le module concerné