#962 [AttendantsTable] add: remove label "Participants -"
Evarisk/Saturne pull request #974
Opened 2024-06-10 08:23 UTC by evarisk-francois

2024-06-21 14:14 UTC, evarisk-micka approved these changes

2024-07-05 10:35 UTC, nicolas-eoxia requested changes

2024-07-05 10:35 UTC, nicolas-eoxia commented on core/tpl/attendants/attendants_table_view.tpl.php
> +print load_fiche_titre(($attendantTableMode == 'advanced') ? $langs->trans($signatoryRole) : '', '', '');
Check signatoryRole sinon il faut qu'il y est participants par défaut

2024-07-19 07:21 UTC, evarisk-micka approved these changes

2024-07-24 09:58 UTC, evarisk-micka approved these changes

2024-08-05 08:40 UTC, nicolas-eoxia commented
Refaire la branche car l'historique de commit ressemble a rien la

2024-08-05 08:40 UTC, closed without merging